# Generated by Django 4.0.5 on 2024-03-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_remove_post_comments_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
    ]
